services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes: [ "qdrant_storage:/qdrant/storage" ]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]
volumes:
  qdrant_storage: {}
  mongo_data: {}
